print("A guy (Verb) into a manhole where he (verb) into a dam full of water. Then he picked up a (Object) then (verb) it into the water. Also he met a person named (proper noun)")
Noun = input("Give me a noun now.\n")
FirstVerb = input("the first verb?\n")
SecondVerb = input("What is your second verb?\n")
ProNoun = input("What is his name?\n")
ThirdVerb = input("What is your third verb?\n")
print(f'A guy {FirstVerb} into a manhole where he {SecondVerb} into a dam full of water. Then he picked up a {Noun} then {ThirdVerb} it into the water. Also he met a person named {ProNoun}')